interface DataTodo {
  avatar: string;
  isRemove: boolean;
  title: string;
  createAt: Date;
  isDone: boolean;
  description: string;
  userName: string;
}

const dataTodo: DataTodo[] = [
  {
    avatar: "1.png",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "A",
  },
  {
    avatar: "2.png",
    isRemove: false,
    title: "Nấu ăn",
    createAt: new Date(),
    isDone: false,
    description: "Nấu ăn trưa",
    userName: "B",
  },
  {
    avatar: "3.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "C",
  },
  {
    avatar: "4.png",
    isRemove: false,
    title: "Lập trình",
    createAt: new Date(),
    isDone: true,
    description: "Lập trình hướng đối tượng",
    userName: "D",
  },
  {
    avatar: "5.png",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "E",
  },
  {
    avatar: "6.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "F",
  },
  {
    avatar: "7.png",
    isRemove: false,
    title: "Lập trình",
    createAt: new Date(),
    isDone: true,
    description: "Lập trình hướng đối tượng",
    userName: "G",
  },
  {
    avatar: "8.png",
    isRemove: false,
    title: "Nấu ăn",
    createAt: new Date(),
    isDone: false,
    description: "Nấu ăn trưa",
    userName: "H",
  },
  {
    avatar: "9.png",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "I",
  },
  {
    avatar: "10.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "K",
  },
  {
    avatar: "11.png",
    isRemove: false,
    title: "Lập trình",
    createAt: new Date(),
    isDone: true,
    description: "Lập trình hướng đối tượng",
    userName: "L",
  },
  {
    avatar: "12.png",
    isRemove: false,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "M",
  },
  {
    avatar: "13.png",
    isRemove: true,
    title: "Lập trình",
    createAt: new Date(),
    isDone: true,
    description: "Lập trình hướng đối tượng",
    userName: "N",
  },
  {
    avatar: "14.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "P",
  },
  {
    avatar: "15.png",
    isRemove: false,
    title: "Nấu ăn",
    createAt: new Date(),
    isDone: false,
    description: "Nấu ăn trưa",
    userName: "Phạm Thanh Q",
  },
  {
    avatar: "16.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "R",
  },
  {
    avatar: "17.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "S",
  },
  {
    avatar: "18.png",
    isRemove: true,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "T",
  },
  {
    avatar: "19.png",
    isRemove: false,
    title: "Học",
    createAt: new Date(),
    isDone: false,
    description: "Ôn tập ",
    userName: "U",
  },
  {
    avatar: "20.png",
    isRemove: true,
    title: "Đọc sách",
    createAt: new Date(),
    isDone: true,
    description: "Đọc sách mới",
    userName: "V",
  },
];

export default dataTodo;
